repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: '^(Assets/ThirdParty|ProjectSettings)'
      - id: pretty-format-json
        args:
          - "--autofix"
        exclude: '^(Assets/ThirdParty|ProjectSettings)'
      - id: trailing-whitespace
        exclude: '^(Assets/|ProjectSettings/)'
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.43.0
    hooks:
      - id: markdownlint
        exclude: '^(Assets/ThirdParty)'
  - repo: local
    hooks:
    -   id: dotnet-format
        name: dotnet-format
        language: system
        entry: dotnet format aiden.sln --include
        types_or: ["c#", "vb"]
        exclude: '^(Assets/ThirdParty)'
