repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: '^(Assets/|ProjectSettings/)'
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: '^(Assets/ThirdParty)'
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.3.2
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: local
    hooks:
    -   id: dotnet-format
        name: dotnet-format
        language: system
        entry: dotnet format aiden.sln --include
        types_or: ["c#", "vb"]
        exclude: '^(Assets/ThirdParty)'
