version: '3.9'

x-base_service: &base_service
  pull_policy: always
  tty: true
  restart: always

services:
  auditory-api:
    <<: *base_service
    profiles: ["auditory-gpu"]
    container_name: auditory-api
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    image: onerahmet/openai-whisper-asr-webservice:latest-gpu
    ports:
      - "${AUDITORY_API_PORT:-9000}:9000"
    environment:
      - ASR_MODEL=${AUDITORY_API_MODEL:-tiny}
      - ASR_ENGINE=${AUDITORY_API_ENGINE:-faster_whisper}

  auditory-api-cpu:
    <<: *base_service
    profiles: ["auditory-cpu"]
    container_name: auditory-api
    deploy: {}
    image: onerahmet/openai-whisper-asr-webservice:latest
    ports:
      - "${AUDITORY_API_PORT:-9000}:9000"
    environment:
      - ASR_MODEL=${AUDITORY_API_MODEL:-tiny}
      - ASR_ENGINE=${AUDITORY_API_ENGINE:-faster_whisper}

  brain-api:
    build: .
    ports:
      - "${BRAIN_API_PORT:-8000}:8000"
    environment:
      - COGNITIVE_API_HOST=cognitive-api
      - COGNITIVE_API_PORT=${COGNITIVE_API_PORT:-11434}
      - COGNITIVE_API_PROTOCOL=${COGNITIVE_API_PROTOCOL:-http}
      - COGNITIVE_MODEL=${COGNITIVE_MODEL:-mistral}
      - REDIS_HOST=redis
    depends_on:
      - redis

  cognitive-api:
    <<: *base_service
    profiles: ["cognitive-gpu"]
    container_name: cognitive-api
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    image: ollama/ollama
    ports:
      - "${COGNITIVE_API_PORT:-11434}:11434"
    environment:
      - COGNITIVE_MODEL=${COGNITIVE_MODEL:-mistral}
    entrypoint: ["sh", "-c", "ollama start & sleep 5 && ollama run ${COGNITIVE_MODEL}"]

  cognitive-api-cpu:
    <<: *base_service
    profiles: ["cognitive-cpu"]
    container_name: cognitive-api
    deploy: {}
    image: ollama/ollama
    ports:
      - "${COGNITIVE_API_PORT:-11434}:11434"
    environment:
      - COGNITIVE_MODEL=${COGNITIVE_MODEL:-mistral}
    entrypoint: ["sh", "-c", "ollama start & sleep 5 && ollama run ${COGNITIVE_MODEL}"]

  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT:-6379}:6379"
    command: redis-server
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  vision-api:
    <<: *base_service
    profiles: ["vision-gpu"]
    container_name: vision-api
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    image: ollama/ollama
    ports:
      - "${VISION_API_PORT:-11435}:11434"
    environment:
      - VISION_API_HOST=${VISION_API_HOST:-localhost}
      - VISION_API_PROTOCOL=${VISION_API_PROTOCOL:-http}
      - VISION_MODEL=${VISION_MODEL:-llava}
    entrypoint: ["sh", "-c", "ollama start & sleep 5 && ollama run ${VISION_MODEL}"]

  vision-api-cpu:
    <<: *base_service
    profiles: ["vision-cpu"]
    container_name: vision-api
    deploy: {}
    image: ollama/ollama
    ports:
      - "${VISION_API_PORT:-11435}:11434"
    environment:
      - VISION_MODEL=${VISION_MODEL:-llava}
    entrypoint: ["sh", "-c", "ollama start & sleep 5 && ollama run ${VISION_MODEL}"]

  vocal-api:
    <<: *base_service
    profiles: ["vocal-gpu"]
    container_name: vocal-api
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    image: ghcr.io/coqui-ai/tts
    ports:
      - "${VOCAL_API_PORT:-5002}:5002"
    entrypoint: ["python3"]
    command: ["TTS/server/server.py", "--model_name", "${VOCAL_API_MODEL:-tts_models/en/ljspeech/tacotron2-DDC}", "--use_cuda", "true"]
    environment:
      - MODEL=${VOCAL_API_MODEL:-tts_models/en/ljspeech/tacotron2-DCA}
      - VOCODER=${VOCAL_API_VOCODER:-vocoder_models/en/ljspeech/multiband-melgan}

  vocal-api-cpu:
    <<: *base_service
    profiles: ["vocal-cpu"]
    container_name: vocal-api
    deploy: {}
    image: ghcr.io/coqui-ai/tts-cpu
    ports:
      - "${VOCAL_API_PORT:-5002}:5002"
    entrypoint: ["python3"]
    command: ["TTS/server/server.py", "--model_name", "${VOCAL_API_MODEL:-tts_models/en/ljspeech/tacotron2-DDC}"]
    environment:
      - MODEL=${VOCAL_API_MODEL:-tts_models/en/ljspeech/tacotron2-DCA}
      - VOCODER=${VOCAL_API_VOCODER:-vocoder_models/en/ljspeech/multiband-melgan}
