[tool.poetry]
name = "aiden"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.79.0"
openai-whisper = { version = "v20231117", markers = "sys_platform == 'linux'" }
python-multipart = "^0.0.5"
soundfile = "^0.10.3.post1"
uvicorn = "^0.18.2"

[tool.poetry.dev-dependencies]
pre-commit = "^3.6.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
