[tool.poetry]
name = "aiden"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.110.1"
httpx = "^0.27.0"
uvicorn = "^0.29.0"
requests = "^2.32.2"
pydantic = "^2.6.4"
redis = "^5.0.4"
# chromadb won't install on at least mac, only needed for docker anyway
chromadb = [{platform = "linux", version = "^0.5.0"}]
langchain-community = "^0.2.5"
langchain-core = "^0.2.7"
langchain-experimental = "^0.0.61"
pillow = "^10.4.0"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.6.2"
pytest = "^8.1.1"
pytest-asyncio = "^0.23.6"
pytest-mock = "^3.14.0"
testcontainers = "^4.5.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
