[tool.poetry]
name = "aiden"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.110.3"
httpx = "^0.27.2"
uvicorn = "^0.29.0"
requests = "^2.32.2"
pydantic = "^2.8.2"
redis = "^5.0.8"
# chromadb won't install on at least mac, only needed for docker anyway
chromadb = [{platform = "linux", version = "^0.5.0"}]
langchain-community = "^0.2.14"
langchain-core = "^0.2.36"
langchain-experimental = "^0.0.61"
pillow = "^10.4.0"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.8.0"
pytest = "^8.3.2"
pytest-asyncio = "^0.23.8"
pytest-mock = "^3.14.0"
testcontainers = "^4.8.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
