[tool.poetry]
name = "aiden"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.110.1"
httpx = "^0.27.0"
uvicorn = "^0.29.0"
requests = "^2.31.0"
pydantic = "^2.6.4"
redis = "^5.0.4"

[tool.poetry.dev-dependencies]
pre-commit = "^3.6.2"
pytest = "^8.1.1"
pytest-asyncio = "^0.23.6"
pytest-mock = "^3.14.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
